version: '3.9'

services:
  mysql:
    image: mysql:8.4.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 1
    restart: unless-stopped

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
      - "${AUTH_SERVICE_DEBUG_PORT}:5005"
    volumes:
      - ./services/auth-service/src:/app/src
      - ./services/auth-service/pom.xml:/app/pom.xml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${AUTH_SERVICE_PORT}/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 1
    restart: on-failure

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend-dev
      - auth-service
      - eureka
    environment:
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro

  eureka:
    build:
      context: ./services/service-registry/service-registry
      dockerfile: Dockerfile.dev
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8082/eureka/
      SERVER_PORT: 8082
    restart: on-failure

  eureka-dashboard:
    build:
      context: ./services/service-registry/service-registry
      dockerfile: Dockerfile.dev
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8082/eureka/
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    restart: on-failure

  frontend-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:${AUTH_SERVICE_PORT}"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173"
      VITE_ALLOWED_HOSTS: "gmail-clone.com,localhost,127.0.0.1"
      VITE_HOST: "0.0.0.0"
      VITE_PORT: "5173"
    depends_on:
      - auth-service

volumes:
  mysql-data:
