services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres17
    restart: unless-stopped

    environment:
      POSTGRES_USER: collabadmin
      POSTGRES_PASSWORD: collabadminsecretpassword
      POSTGRES_DB: collabdb

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\""]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

volumes:
  pgdata:
